# Generated by Django 5.2.17 on 2026-09-03 17:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('origen', models.CharField(choices=[('proveedor', 'Proveedor'), ('propia', 'Propia')], max_length=20)),
                ('fecha_alta', models.DateField()),
                ('contenedor', models.CharField(choices=[('suelo', 'Suelo'), ('maceta', 'Maceta')], max_length=20)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('muerta', 'Muerta'), ('vendida', 'Vendida'), ('regalada', 'Regalada'), ('descartada', 'Descartada'), ('seleccionada', 'Seleccionada')], default='activa', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('token_publico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('publico_activo', models.BooleanField(default=False)),
                ('ultima_altura', models.FloatField(blank=True, null=True)),
                ('ultimo_diametro', models.FloatField(blank=True, null=True)),
                ('ultima_fecha_medicion', models.DateField(blank=True, null=True)),
                ('tasa_crecimiento', models.FloatField(blank=True, null=True)),
                ('indice_esbeltez', models.FloatField(blank=True, null=True)),
                ('n_eventos_fitosanitarios', models.PositiveIntegerField(default=0)),
                ('score_vigor_actual', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_sanidad_actual', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bandeja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nursery.bandeja')),
                ('etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nursery.etapafenologica')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nursery.lote')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nursery.proveedor')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nursery.variedad')),
            ],
        ),
    ]
