# Generated by Django 5.2.17 on 2026-09-03 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0003_evaluacion_medicion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('producto', models.CharField(blank=True, max_length=200)),
                ('dosis', models.CharField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('plantas', models.ManyToManyField(blank=True, to='nursery.planta')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nursery.tipoevento')),
            ],
        ),
    ]
