# Generated by Django 5.2.17 on 2026-09-03 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0004_evento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='fotos/%Y/%m/')),
                ('fecha', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nursery.evento')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursery.planta')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nursery.tipofoto')),
            ],
        ),
    ]
