# Generated by Django 5.2.17 on 2026-09-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0005_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planta',
            name='motivo_baja',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
