# Generated by Django 5.2.17 on 2026-09-04 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0006_planta_fecha_baja_planta_motivo_baja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('activa', 'Activa'), ('muerta', 'Muerta'), ('vendida', 'Vendida'), ('regalada', 'Regalada'), ('descartada', 'Descartada'), ('seleccionada', 'Seleccionada')], max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('activa', 'Activa'), ('muerta', 'Muerta'), ('vendida', 'Vendida'), ('regalada', 'Regalada'), ('descartada', 'Descartada'), ('seleccionada', 'Seleccionada')], max_length=20)),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_estado', to='nursery.planta')),
            ],
        ),
    ]
